### ISSUE TITLE
Add live weather telling web page 

### ISSUE THREAD

**Issue by AbhishekKumar2002** [SquaredR98/Front-End-Projects-HTML-CSS#10]
Hi @SquaredR98, I would like to add Weather telling web page which will tell you about the live weather of the place you search. I will use Simple HTML, CSS and JAVASCRIPT.

**Comment by SquaredR98** [comment]
Sorry, man didn't see this earlier if it was meant for hactoberfest let's try next year. I was heavily busy this month so I was unable to merge any request myself. My friend were doing it for their PR so it might have been missed. @AbhishekKumar2002

**Comment by AbhishekKumar2002** [comment]
@SquaredR98 It's ok Sir, I understand that sometimes we get busy very much. So, it's ok and my all 4 PR's have been accepted.
